author: oktavyanha
email: oktavyanhardiyono@gmail.com
theme: minima
title: A Brief Introduction of Me
description: > # this means to ignore newlines until "baseurl:"
  A Beginner in quantum realm. has create thousands of probability, less observed in reality
# social links
twitter_username: OktavyanH # DO NOT include the @ character, or else the build will fail!
github_username:  oktavyanha # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
